import { ProductCategory } from '@/types/generation'

export const FEATURE_TEMPLATES: Record<ProductCategory, string[]> = {
  saas: [
    'User authentication and role-based access',
    'Team collaboration and real-time updates',
    'Customizable dashboards and analytics',
    'API integrations with popular tools',
    'Automated workflows and task management',
    'Advanced reporting and data exports',
    'Mobile app for iOS and Android',
    'Single sign-on (SSO) and OAuth support',
    'Audit logging and compliance tracking',
    'Automated backups and disaster recovery',
  ],
  b2c_app: [
    'Social login and authentication',
    'Personalized user profiles',
    'Push notifications and alerts',
    'In-app messaging and chat',
    'Gamification and rewards system',
    'User-generated content sharing',
    'Community and social features',
    'Search and discovery',
    'Offline mode support',
    'Dark mode theme',
  ],
  marketplace: [
    'Seller and buyer account management',
    'Product listing and marketplace catalog',
    'Search, filtering, and recommendations',
    'Secure payment processing',
    'Escrow and dispute resolution',
    'Seller ratings and reviews',
    'Messaging between buyers and sellers',
    'Order tracking and delivery management',
    'Commission and payout system',
    'Fraud detection and prevention',
  ],
  hardware: [
    'Mobile app for device control',
    'Cloud connectivity and sync',
    'Real-time notifications',
    'Data logging and analytics',
    'Over-the-air (OTA) updates',
    'Multi-device support',
    'Scheduling and automation',
    'Integration with smart home systems',
    'Battery and power management',
    'Security and encryption',
  ],
  service: [
    'Appointment scheduling system',
    'Client management and CRM',
    'Invoice and payment processing',
    'Team scheduling and coordination',
    'Resource allocation and planning',
    'Service quality tracking',
    'Client portal and self-service',
    'Marketing and lead management',
    'Analytics and reporting',
    'Multi-location support',
  ],
  community: [
    'User profiles and social graphs',
    'Discussion forums and threads',
    'Content moderation tools',
    'User-generated content platform',
    'Community guidelines and policies',
    'Events and meetups',
    'Direct messaging',
    'Notifications and feeds',
    'Content discovery and recommendations',
    'Admin dashboard and analytics',
  ],
  ai_tool: [
    'AI model serving and inference',
    'Batch processing capabilities',
    'Real-time API endpoints',
    'Model fine-tuning and customization',
    'Prompt engineering interface',
    'Usage monitoring and quotas',
    'Integration with popular frameworks',
    'Webhook support for events',
    'Advanced analytics and insights',
    'Version control for models',
  ],
}

export function getDefaultFeatures(category: ProductCategory): string[] {
  return FEATURE_TEMPLATES[category] || FEATURE_TEMPLATES.saas
}
