import { ProductCategory } from '@/types/generation'

export const FEATURE_TEMPLATES: Record<ProductCategory, string[]> = {
  saas: [
    'User authentication and role-based access',
    'Team collaboration and real-time updates',
    'Customizable dashboards and analytics',
    'API integrations with popular tools',
    'Automated workflows and task management',
    'Advanced reporting and data exports',
    'Mobile app for iOS and Android',
    'Single sign-on (SSO) and OAuth support',
    'Audit logging and compliance tracking',
    'Automated backups and disaster recovery',
  ],
  b2c_app: [
    'Social login and authentication',
    'Personalized user profiles',
    'Push notifications and alerts',
    'In-app messaging and chat',
    'Gamification and rewards system',
    'User-generated content sharing',
    'Community and social features',
    'Search and discovery',
    'Offline mode support',
    'Dark mode theme',
  ],
  marketplace: [
    'Seller and buyer account management',
    'Product listing and marketplace catalog',
    'Search, filtering, and recommendations',
    'Secure payment processing',
    'Escrow and dispute resolution',
    'Seller ratings and reviews',
    'Messaging between buyers and sellers',
    'Order tracking and delivery management',
    'Commission and payout system',
    'Fraud detection and prevention',
  ],
  hardware: [
    'Mobile app for device control',
    'Cloud connectivity and sync',
    'Real-time notifications',
    'Data logging and analytics',
    'Over-the-air (OTA) updates',
    'Multi-device support',
    'Scheduling and automation',
    'Integration with smart home systems',
    'Battery and power management',
    'Security and encryption',
  ],
  service: [
    'Appointment scheduling system',
    'Client management and CRM',
    'Invoice and payment processing',
    'Team scheduling and coordination',
    'Resource allocation and planning',
    'Service quality tracking',
    'Client portal and self-service',
    'Marketing and lead management',
    'Analytics and reporting',
    'Multi-location support',
  ],
  community: [
    'User profiles and social graphs',
    'Discussion forums and threads',
    'Content moderation tools',
    'User-generated content platform',
    'Community guidelines and policies',
    'Events and meetups',
    'Direct messaging',
    'Notifications and feeds',
    'Content discovery and recommendations',
    'Admin dashboard and analytics',
  ],
  ai_tool: [
    'AI model serving and inference',
    'Batch processing capabilities',
    'Real-time API endpoints',
    'Model fine-tuning and customization',
    'Prompt engineering interface',
    'Usage monitoring and quotas',
    'Integration with popular frameworks',
    'Webhook support for events',
    'Advanced analytics and insights',
    'Version control for models',
  ],
  mobile_app: [
    'Push notifications and alerts',
    'Offline functionality and sync',
    'Biometric authentication (fingerprint, face ID)',
    'Device sensor integration (GPS, camera, accelerometer)',
    'Local data storage and caching',
    'Native performance optimization',
    'Background task processing',
    'Deep linking and app shortcuts',
    'App store optimization and updates',
    'In-app purchase and subscription management',
  ],
  web_app: [
    'Responsive and adaptive design',
    'Progressive web app (PWA) capabilities',
    'Cross-browser compatibility',
    'Real-time synchronization',
    'Client-side offline support',
    'Advanced API integrations',
    'Session management and authentication',
    'Data persistence and local storage',
    'WCAG accessibility compliance',
    'Performance optimization and caching',
  ],
  fintech: [
    'Two-factor authentication and security',
    'Real-time transaction processing',
    'Portfolio and asset tracking',
    'Payment gateway integration',
    'KYC/AML compliance automation',
    'Transaction history and statements',
    'Budget tracking and financial analytics',
    'Investment performance analysis',
    'Secure document management',
    'Regulatory reporting and audit trails',
  ],
  healthcare: [
    'HIPAA compliance and data encryption',
    'Electronic health records (EHR)',
    'Patient appointment scheduling',
    'Telemedicine and video consultations',
    'Prescription management system',
    'Medical imaging and file storage',
    'Patient portal and self-service',
    'Lab results and diagnostic integration',
    'Insurance verification and billing',
    'Medical data interoperability (HL7, FHIR)',
  ],
  edtech: [
    'Learning management system (LMS)',
    'Student progress tracking and analytics',
    'Interactive content and multimedia',
    'Adaptive assessment and testing',
    'Collaboration and group projects',
    'Certificate and credential issuance',
    'Content library and resource management',
    'Parent and instructor dashboards',
    'Gamification and achievement badges',
    'Integration with educational standards',
  ],
  gaming: [
    'Multiplayer and networking support',
    'In-app purchases and virtual currency',
    'Leaderboards and achievement system',
    'Social integration and sharing',
    'Cross-platform play support',
    'Anti-cheat and fraud detection',
    'In-game economy and trading',
    'Analytics and user behavior tracking',
    'Community features and chat',
    'Cloud save and synchronization',
  ],
  social: [
    'User profiles and profiles customization',
    'Direct messaging and notifications',
    'Feed, timeline, and content discovery',
    'User-generated content and media upload',
    'Social graph and relationship management',
    'Real-time updates and activity feeds',
    'Search and trending features',
    'Content moderation and safety tools',
    'Privacy controls and permissions',
    'Integration with third-party platforms',
  ],
}

export function getDefaultFeatures(category: ProductCategory): string[] {
  return FEATURE_TEMPLATES[category] || FEATURE_TEMPLATES.saas
}
